### ISSUE TITLE
[Discussion] What is our project for?

### ISSUE THREAD

**Issue by baejaeho18** [2023OSSTEAM/2023_oss_team#1]

**Comment by leeyoonjin22** [comment]
Ladder Game

**Comment by baejaeho18** [comment]
What could be a target of CRUD?
User's name?

**Comment by baejaeho18** [comment]
Sry for mistake.  This issue doesn't closed yet

**Comment by baejaeho18** [comment]
As we discussed, user name and each game's penalty could be a target of CRUD
